name: Report an issue with the documentation of Home Assistant Voice Preview Edition
description: Report a documentation issue
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting documentation isses only!

        If you have a feature or enhancement request, please use the [feature request][fr] section of our [Community Forum][fr].

        [fr]: https://community.home-assistant.io/c/feature-requests

        If you experience an issue with the Home Assistant Voice Preview Edition software, please use the [Voice PE issue tracker][vpe gh]. Before logging an issue, please check the [list of issues][vpe gh issue tracker].
        
        [vpe gh] https://github.com/esphome/home-assistant-voice-pe
        [vpe gh issue tracker] https://github.com/esphome/home-assistant-voice-pe/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen


  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you spotted in the documentation.
        Provide a clear and concise description of what the problem is.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Link to the page
      description: >-
        Provide a link to the page where you spotted the issue.
